version: '3'

services:
  api-1-service:
    build: ./api
    ports:
      - 5001:5000

  api-2-service:
    build: ./api
    ports:
      - 5002:5000

    api-3-service:
    build: ./api
    ports:
      - 5003:5000
